tasktracker/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('add-task/', views.add_task, name="add-task"),
    path('delete-task/<int:pk>', views.delete_task, name="delete-task"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('signin/', views.signin_user, name="signin"),
]

yolo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('tasktracker.urls')),
]

tasktracker/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    acc_name = models.CharField(max_length=50)

    def __str__(self):
        return self.acc_name

class Task(models.Model):
    account = models.ForeignKey(Account, null=True, on_delete=models.CASCADE)
    task_name = models.CharField(max_length=200, null=False)
    task_description = models.CharField(max_length=200, null=False)
    task_date = models.DateField()
    date_reached = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.task_name

tasktracker/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import Task

class DateInput(forms.DateInput):
    input_type = 'date'

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task_name', 'task_description', 'task_date']
        widgets = {
            'task_date': DateInput(),
        }

tasktracker/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Task
from .forms import TaskForm

from datetime import datetime

# Create your views here.
def home(request):
    if request.user.is_authenticated:
        form = TaskForm()
        tasks = Task.objects.filter(account=request.user.account)
        today = datetime.now().date() # .strftime('%Y-%m-%d')

        for task in tasks:
            if today > task.task_date:
                task.date_reached = True

        if len(tasks) > 0:
            avail = True
        else:
            avail = False


        context = {'form': form, 'tasks': tasks, 'avail': avail}
        return render(request, 'tasktracker/task.html', context)
    else:
        return redirect('login')

def add_task(request):
    # If the user is authenticated and has posted a task
    if request.method == 'POST':
        form = TaskForm(data=request.POST)
        if form.is_valid():
            form.save()

            # Getting the last saved task
            saved_form = Task.objects.latest('created')
            saved_form.account = request.user.account
            saved_form.save()

            return redirect("home")

def delete_task(request, pk):
    try:
        task_to_delete = Task.objects.get(pk=pk)
        task_to_delete.delete()

        return redirect('home')
    except:
        pass

def login_user(request):
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
        except:
            # If user does not exist
            return redirect('signin')

        # If user exists log them in
        user = authenticate(request, username=username, password=password)
        print(user)
        if user is not None:
            login(request, user)
            return redirect('home')

    return render(request, 'tasktracker/login.html')

def signin_user(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            login(request, user)
            return redirect('home')

    context = {'form':form}
    return render(request, 'tasktracker/signin.html', context)

def logout_user(request):
    logout(request)
    return redirect('login')

tasktracker/templates/tasktracker/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>YOLO - Task Tracker</title>

    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- CUSTOM CSS -->
    <link rel="stylesheet" href="{% static 'css/task.css' %}">
</head>
<body>
    <div class="container d-flex justify-content-center align-items-center" style="padding-top: 10%;" >
        <form method="post">
          {% csrf_token %}
          <h1 class="info-text text-uppercase">Login Here</h1>
          <p class="lead" style="font-size: 14px;">Enter credenrials...</p>
          <div class="form-group mt-2">
            <input type="text" class="form-control" name="username" aria-describedby="emailHelp" placeholder="Enter username">
          </div>
          <div class="form-group mt-3">
            <input type="password" class="form-control" name="password" placeholder="Password">
          </div>
          <div class="form-group mt-2">
            <a href="#">Forgot password?</a>
          </div>
          <button type="submit" class="btn btn-primary btn-block mt-2" style="width: 100%;">Login</button>
          <div class="form-group mt-2">
              <p>Don't have an account? <a href="{% url 'signin' %}">Sign in</a></p>
          </div>
        </form>
    </div>
</body>
</html>

tasktracker/templates/tasktracker/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>YOLO - Task Tracker</title>

    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- CUSTOM CSS -->
    <link rel="stylesheet" href="{% static 'css/task.css' %}">
</head>
<body>
    <div class="container d-flex justify-content-center align-items-center" style="padding-top: 10%;" >
        <form method="post">
          {% csrf_token %}
          <h1 class="info-text text-uppercase">Sign in</h1>
          <p class="lead" style="font-size: 14px;">Enter credenrials...</p>
          <div class="form-group mt-2">
            <input type="text" class="form-control" name="username" aria-describedby="emailHelp" placeholder="Enter username">
          </div>
          <div class="form-group mt-2">
            <input type="email" class="form-control" name="email" aria-describedby="emailHelp" placeholder="Enter email">
          </div>
          <div class="form-group mt-3">
            <input type="password" class="form-control" name="password1" placeholder="Password">
          </div>
          <div class="form-group mt-3">
            <input type="password" class="form-control" name="password2" placeholder="Re-enter password">
          </div>
          <button type="submit" class="btn btn-primary btn-block mt-2" style="width: 100%;">Submit</button>
          <div class="form-group mt-2">
              <p>Already have an account? <a href="{% url 'login' %}">Login</a></p>
          </div>
        </form>
    </div>
</body>
</html>

tasktracker/templates/tasktracker/task.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>YOLO - Task Tracker</title>
    
    <!-- FONT AWESOME -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- CUSTOM CSS -->
    <link rel="stylesheet" href="{% static 'css/task.css' %}">
</head>
<body>
    <div class="container mt-4">
        <div class=" mb-4">
            <div class="bg-primary text-white" style="
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            padding: 10px 20px;">
                <h2>Your Tasks</h2>
                <div>
                    <button type="button" class="btn btn-secondary mx-2" data-bs-toggle="modal" data-bs-target="#task-modal" data-bs-whatever="@mdo">Add</button>
                    <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
                </div>
            </div>
        </div>
        <div class="list-group mt-2">
            {% if avail %}
                {% for task in tasks %}
                    <!-- To show offcanvas for each task -->
                    <!-- task-privew-task.id -->
                    <!-- Without this the offcanvas will display the first task all through -->
                    <a class="list-group-item list-group-item-action flex-column align-items-start" data-bs-toggle="offcanvas" href="#task-preview-{{ task.id}}" role="button" aria-controls="task-preview">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="text-primary mb-1" style="text-transform: uppercase;">{{ task.task_name }}</h5>
                            {% if task.date_reached %}
                                <i class="fa-sharp fa-regular fa-bell text-danger"></i>
                            {% else %}
                                <i class="fa-sharp fa-regular fa-bell text-primary"></i>
                            {% endif %}
                        </div>
                        <small class="text-secondary">{{ task.task_date }}</small>
                        <p class="mb-1">{{ task.task_description }}</p>
                    </a>

                    <!-- Card to view task -->
                    <div class="offcanvas offcanvas-start" tabindex="-1" id="task-preview-{{ task.id}}" aria-labelledby="task-preview-label">
                        <div class="offcanvas-header">
                            <h5 class="offcanvas-title text-primary" id="task-preview-label" style="text-transform: uppercase;">{{ task.task_name }}</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                        </div>
                        <div class="offcanvas-body">
                            <div>
                                <div style="display: flex; justify-content: space-between;">
                                    <small class="text-muted">{{ task.task_date }}</small>
                                    {% if task.date_reached %}
                                        <i class="fa-sharp fa-regular fa-bell text-danger"></i>
                                    {% else %}
                                        <i class="fa-sharp fa-regular fa-bell text-primary"></i>
                                    {% endif %}
                                </div>
                                <p>{{ task.task_description }}</p>
                            </div>
                            <a href="{% url 'delete-task' task.id %}" class="btn btn-danger" type="button" style="position: absolute; bottom: 20px; right: 20px;">Delete</a>
                        </div>
                    </div>
                    
                {% endfor %}
            {% else %}
                <div class="container">
                    <h1 class="lead">No Tasks available...</h1>
                </div>
            {% endif %}
        </div>
    </div>


    <!-- MODAL FOR ADDING TASKS -->
    <div class="modal fade" id="task-modal" tabindex="-1" role="dialog" aria-labelledby="task-modalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="task-modalLabel">Add Task</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" action="add-task/">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_task_name" class="col-form-label">Task Name:</label>
                            <!-- <input type="text" class="form-control" name="-task_name"> -->
                            {{ form.task_name }}
                        </div>
                        <div class="form-group">
                            <label for="id_task_description" class="col-form-label">Description:</label>
                            <!-- <input class="form-control" name="task_description"> -->
                            {{ form.task_description }}
                        </div>
                        <div class="form-group">
                            <label for="id_task_date" class="col-form-label">Date:</label>
                            <!-- <input type="date" class="form-control" name="task_date"> -->
                            {{ form.task_date }}
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success mt-2" style="width: 100%;">Add Task</button>
                            <!-- <button type="button" class="btn btn-warning" data-bs-dismiss="modal">Close</button> -->
                        </div>
                    </form>
                </div>
                <!-- <div class="modal-footer">
                    <button type="submit" class="btn btn-success">Add Task</button>
                    <button type="button" class="btn btn-warning" data-bs-dismiss="modal">Close</button>
                </div> -->
            </div>
        </d>
    </div>

    <script>
        document.querySelector('#id_task_name').className += 'form-control';
        document.querySelector('#id_task_description').className += 'form-control';
        document.querySelector('#id_task_date').className += 'form-control';
    </script>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script>
        $('#task-modal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget) // Button that triggered the modal
        var recipient = button.data('whatever') // Extract info from data-* attributes
        // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
        // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
        var modal = $(this)
        modal.find('.modal-title').text('New message to ' + recipient)
        modal.find('.modal-body input').val(recipient)
        })
    </script>
</body>
</html>